AndrewBlog/Models/BlogViewModels/CreateVIewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AndrewBlog.Data.Models;
using Microsoft.AspNetCore.Http;

namespace AndrewBlog.Models.BlogViewModels
{
    public class CreateVIewModel
    { 
        [Required,Display(Name ="Header Image")]
        public IFormFile BlogHeaderImage { get; set; }
        public Blog Blog { get; set; }
    }
}

AndrewBlog/Models/BlogViewModels/EditViewModel.cs
using AndrewBlog.Data.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AndrewBlog.Models.BlogViewModels
{
    public class EditViewModel
    {
        [Display(Name = "Header Image")]
        public IFormFile BlogHeaderImage { get; set; }
        public Blog Blog { get; set; } 
    }
}

AndrewBlog/Controllers/BlogController.cs
using AndrewBlog.BusinessManagers.Interfaces;
using AndrewBlog.Data.Models;
using AndrewBlog.Models.BlogViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AndrewBlog.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogBusinessManager blogBusinessManager;
        public BlogController(IBlogBusinessManager blogBusinessManager) 
        {
            this.blogBusinessManager = blogBusinessManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View(new CreateVIewModel());
        }
        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await blogBusinessManager.GetEditViewModel(id, User);
            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }
        [HttpPost]
        public async Task<IActionResult> Add(CreateVIewModel createViewModel)
        {
          
            await blogBusinessManager.CreateBlog(createViewModel, User);
            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editViewModel)
        {
          
          var actionResult = await blogBusinessManager.UpdateBlog(editViewModel, User);
            if (actionResult.Result is null)
                return RedirectToAction("Edit", new { editViewModel.Blog.Id });

            return actionResult.Result;
        }
    }
}

AndrewBlog/ViewComponents/AdminFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AndrewBlog.ViewComponents
{
    public class AdminFooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

AndrewBlog/ViewComponents/AdminSideNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AndrewBlog.ViewComponents
{
    public class AdminSideNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

AndrewBlog/ViewComponents/AdminTopNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AndrewBlog.ViewComponents
{
    public class AdminTopNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

AndrewBlog/Views/Blog/Create.cshtml
@model CreateVIewModel

<div class="container-fluid">
    <h1 class="mt-4">Create</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <form asp-controller="Blog" asp-action="Add" method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <i class="fas fa-pen-fancy mr-1"></i>
                        Write a Post
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="BlogHeaderImage"></label>
                            <div class="custom-file">
                                <input asp-for="BlogHeaderImage" class="custom-file-input" accept="image/*" />
                                <label class="custom-file-label">Choose file</label>
                            </div>
                            <span asp-validation-for="BlogHeaderImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Title"></label>
                            <input asp-for="Blog.Title" class="form-control" required />
                            <span asp-validation-for="Blog.Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Content"></label>
                            <textarea asp-for="Blog.Content" class="form-control textarea" rows="8"></textarea>
                            <span asp-validation-for="Blog.Content" class="text-danger"></span>
                        </div>
                    </div>



                    <div class="card-footer">
                        <div class="form-group">
                            <p class="text-muted"> Publish mow or save for later edits</p>
                            <label>Publish now?</label>
                            <input type="checkbox" data-toggle="toggle" asp-for="Blog.Published" />
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>

                    </div>
                </form>
            </div>
            
        </div>
        </div>
    </div>

@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.textarea'))
            .catch(error => {
                console.error(error);
            });
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

AndrewBlog/Views/Blog/Edit.cshtml
@model EditViewModel

<div class="container-fluid">
    <h1 class="mt-4">Edit</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <form asp-controller="Blog" asp-action="Update" method="post" enctype="multipart/form-data">
                    <input asp-for="Blog.Id" readonly hidden />
                    <div class="card-header">
                        <i class="fas fa-pen-fancy mr-1"></i>
                        Edit this blog
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="BlogHeaderImage"></label>
                            <div class="custom-file">
                                <input asp-for="BlogHeaderImage" class="custom-file-input" accept="image/*" />
                                <label class="custom-file-label">Choose file</label>
                            </div>
                            <span asp-validation-for="BlogHeaderImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Title"></label>
                            <input asp-for="Blog.Title" class="form-control" required />
                            <span asp-validation-for="Blog.Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Content"></label>
                            <textarea asp-for="Blog.Content" class="form-control textarea" rows="8"></textarea>
                            <span asp-validation-for="Blog.Content" class="text-danger"></span>
                        </div>
                    </div>



                    <div class="card-footer">
                        <div class="form-group">
                            <p class="text-muted"> Publish mow or save for later edits</p>
                            <label>Publish now?</label>
                            <input type="checkbox" data-toggle="toggle" asp-for="Blog.Published" />
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>

                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.textarea'))
            .catch(error => {
                console.error(error);
            });
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

AndrewBlog/Views/Blog/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AndrewBlog/Views/Blog/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/css/stylesAdmin.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    @RenderSection("Styles", false);
</head>
<body class="sb-nav-fixed">
    @await Component.InvokeAsync("AdminTopNav")
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            @await Component.InvokeAsync("AdminSideNav")
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            @await Component.InvokeAsync("AdminFooter")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scriptsAdmin.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>